plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/rubz/.lp-deploy/articlemag"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Robots-Tag = "all"