plugins = []

[functions]

[functions."*"]

[build]
publish = "/Users/rubz/.lp-deploy/articlemag"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Robots-Tag = "all"

[[redirects]]
from = "/riviera-silver-fox/*"
to = "/fr/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/the-detail-after-50/*"
to = "/us/"
status = 301.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/"
to = "/fr/"
status = 302.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]